### ISSUE TITLE
where to put .dll

### ISSUE THREAD

**Issue by YTjoschi64xd** [Decoder0007/PlatformerMode#1]
where

**Comment by Ez4MeGitHub** [comment]
search how to inject dlls or how to install dlls

**Comment by Decoder0007** [comment]
depends what mod loader you are using. EG megahack is the extensions folder

**Comment by YTjoschi64xd** [comment]
well i have mega hack v5

**Comment by Decoder0007** [comment]
Click inject Dll in megahack then select the dll file
